import path from "path";
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
import webpack from "webpack";
import nodeExternals from "webpack-node-externals";

export default {
  entry: path.resolve(__dirname, 'src/TideCalendar.js'),
  output: {
    iife: false,
    path: path.resolve(__dirname, 'appscript'),
    filename: 'TideCalendar.gs'
  },
  mode: 'production',
  target: ['web', 'es5'],
  // Without externals, ical gets pulled in to the pack
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: [ /node_modules/ ],
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              [
                '@babel/preset-env',
                {
                  targets: {
                    // Google Apps Script uses an older JavaScript runtime
                    ie: '11'
                  },
                  modules: false
                }
              ]
            ]
          }
        }
      }
    ]
  },
  plugins: [
    // Banner plugin to add comments or strip certain patterns if needed
    new webpack.BannerPlugin({
      banner: '// Google Apps Script Bundle\n// Generated by webpack',
      raw: true,
      entryOnly: true
    })
  ],
  optimization: {
    minimize: false, // Keep code readable for debugging in Apps Script
    concatenateModules: true // Merge modules into single scope
  },
  resolve: {
    modules: ['node_modules', 'src', 'bin'],
    extensions: ['.js']
  }
};
